name: Security Scan

on:
  push:
    branches:
      - master

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '19'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install

      - name: Run OWASP ZAP Scan
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip
          pip3 install --user zapcli
          zap-cli start
          zap-cli quick-scan -u http://localhost:8090 --output /tmp/scan-report.json

      - name: Convert Scan Report to HTML
        run: |
          pip3 install --user zap-cli-reports
          zap-cli report -f html -o /home/runner/work/TwitterUserService/TwitterUserService/quick-scan-report.html -f /tmp/scan-report.json

      - name: Upload Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: Security Scan Report
          path: /home/runner/work/TwitterUserService/TwitterUserService/quick-scan-report.html


